### ISSUE TITLE
How to add Cards features like PayPal to our project ??? 

### ISSUE THREAD

**Issue by chegmarco1989** [bavix/laravel-wallet#125]
Hello. 

This is a real project. We want to launch an electronic payment application based on Laravel Bavix Ewallet and we wish to add him a feature of cards (prepaid, credit and flow). This feature will have to allow our customers to make deposits and withdrawals with their different cards. So we wish to know if this library can help us put in place such a functionality exactly as Paypal. 

Thank you.

**Comment by saad3074** [comment]
@chegmarco1989 I think its good if we use wallets for virtual currencies like all deposits are made from 1 admin account and all payments are transferred to 1 admin account . 
but you can make it dynamic as make separate transaction table and record all those live transactions.

 I already used this as a virtual wallets as all users can transferred or deposit to Company account and on purchase time company will pay on users behalf.


**As someone else will explain better if they use direct payment to wallets **

**Comment by rez1dent3** [comment]
@chegmarco1989 Hello.  
The library is as abstract as possible.  I have been using it on the production for more than nine months and solve problems with the help of library extensions and patches (you can see changelog).  I think screwing PayPal will not be difficult for you.  Then how to act is up to you.  One of the users requested support for laravel/cashier (you can find the issue).  In my project, using acquiring, they buy a “point” (internal currency), which is implemented over the bavix/laravel-wallet-swap extension.  There were problems with the “race condition”, the problem was solved in bavix/laravel-wallet-vacuum.  I tried to develop a library as extensible as possible.

**Comment by rez1dent3** [comment]
I close the issue, there are questions - create a new one.
