### ISSUE TITLE
withdraw interest

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#260]
Hello please i added a new colume called interest_balance to the migration table of wallet and i want user to be able to withdraw either the main balance or interest balance, please need help with logic

**Comment by rez1dent3** [comment]
Hey. If you add a column to the table, then nothing can be done. Because you will have to completely duplicate all the functionality for the new field in the database. I recommend using two wallets.

Create two wallets.
```php
$cash = $user->createWallet(['name' => 'USD']); // My cash account
$interest = $user->createWallet(['name' => 'USD Percent']); // My account for interest
```

Now closer to work. A person will work with one wallet, and interest will be charged on the other.
```php
$cash->deposit(100);
// ...You accrue interest on another account
```

This is what a withdrawal will look like.
```php
$interest->withdraw(5);
```

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
