### ISSUE TITLE
[question] Balance cache

### ISSUE THREAD

**Issue by mattvb91** [bavix/laravel-wallet#413]
Just wondering about the correct procedure here.

I had the cache driver set to `array` for initial testing and ended up getting wrong balances and deposits during transfers due to me running a job inside its own docker container (which would have kept its own balance cache) and my seperate php server (Which again would have kept its own balance cache).

Changing the cache driver to redis which both containers share has fixed the issue which makes sense but it has made me a bit paranoid. Is it possible to just deactivate the cache completely and always read the db values?

Should I be using `wallet->refreshBalance()` all the time just incase before making a transaction?

EDIT: just noticed in 7.0.0 release the refresh command was removed.

**Comment by rez1dent3** [comment]
Hello.

> EDIT: just noticed in 7.0.0 release the refresh command was removed.

Not certainly in that way. It has been moved to a separate repository. Use the command only as a last resort.
https://github.com/bavix/laravel-wallet-warmup

> I had the cache driver set to array for initial testing and ended up getting wrong balances and deposits during transfers due to me running a job inside its own docker container (which would have kept its own balance cache) and my seperate php server (Which again would have kept its own balance cache).

If the array driver is enabled, then assume that you have no atomicity at all. If there are two requests, they will both be executed.

If you configure a lock service, then such requests will go to the "queue". I recommend everyone to use redis because it is single threaded and guarantees data atomicity.

> Is it possible to just deactivate the cache completely and always read the db values?

You can, but in this case you will have to inherit from the Wallet model and override the getBalanceAttribute method. 
I do not recommend doing this, because the following case may turn out.

```php
$wallet->balanceInt; // 1000
$transaction = $wallet->withdraw(1000, null, false); // not confirm. 
// we checked that there is money, created an unconfirmed transaction

$wallet->balanceInt; // 1000

// at that moment another request came and all the money was debited from the account
// any logic...

$user->safeConfirm($transaction); // true.. 
$wallet->balanceInt; // -1000
```

This is an example why I am not using a column from a database.

Let's take a look at another case?
```php
$wallet->refresh(); // Just in case
$wallet->balanceInt; // 1000
// Another request has already charged your money. But the model will not know about it. balance=0
$wallet->withdraw(1000); // balance=-1000
```

> Should I be using wallet->refreshBalance() all the time just incase before making a transaction?

No, this is an extreme measure. If you have a lot of transactions in the table, then this query can be fatal for the sale. The cache contains up-to-date information.

Version 7.1 is currently in development, which will add support for transactions between the cache service and the database. More details here #412
