### ISSUE TITLE
[Warning] Infinity loop when use traits HasWallet

### ISSUE THREAD

**Issue by nvchungdl** [bavix/laravel-wallet#805]
**Describe the bug**
 Infinity loop when use traits HasWallet with model already have column "balance" in table

**To Reproduce**
1. create table users with column: balance
2. implement HasWallet to model User
3. return User::find(1000000);

<img width="1399" alt="Screenshot 2023-11-21 at 16 32 56" src="https://github.com/bavix/laravel-wallet/assets/23648103/27b81062-39f9-47d9-a00c-485b45d30df8">

**Comment by rez1dent3** [comment]
Hello. This is not a bug, but expected behavior. The balance column is declared in HasWallet:
https://github.com/bavix/laravel-wallet/blob/18448234e9af73fdf31bd9a5ca9a26fd34e56eca/src/Traits/HasWallet.php#L64

You need to use the multi-wallet functionality (HasWallets trait). HasWallet is not suitable for your case.
