### ISSUE TITLE
How can new columns be added in transactions in version 10.x?

### ISSUE THREAD

**Issue by hamedkhorasani** [bavix/laravel-wallet#845]
Hello **@rez1dent3** 
I appreciate your help in creating this package. 
I need a new field named '**transaction_name**' for grouping deposits and withdrawals, along with a '**parent**' field. In version 10.x, I was unable to add two new fields to the transaction.
If possible, could you explain this with an example?

**Comment by rez1dent3** [comment]
Hello, @hamedkhorasani. 

I would not recommend adding new fields, because... There is a meta field of the json type that covers most cases. BUT there is a need, then you need to do this:

1. Override `TransactionDtoTransformerInterface` interface:

https://github.com/bavix/laravel-wallet/blob/ae394c5e8cb22082dfea181fd2db59522227e818/tests/Infra/Transform/TransactionDtoTransformerCustom.php#L18-L28

2. Override `Transaction` model:

https://github.com/bavix/laravel-wallet/blob/ae394c5e8cb22082dfea181fd2db59522227e818/tests/Infra/PackageModels/Transaction.php#L14-L17

3. Replace the objects in the wallet.php file.

https://github.com/bavix/laravel-wallet/blob/ae394c5e8cb22082dfea181fd2db59522227e818/config/config.php#L134

https://github.com/bavix/laravel-wallet/blob/ae394c5e8cb22082dfea181fd2db59522227e818/config/config.php#L168

4. Migration:

https://github.com/bavix/laravel-wallet/blob/a9c30b7bac2d4ab354db74e0828de432203a177b/tests/migrations/2019_09_19_191432_alter_column_transaction_table.php#L13-L17

---


In the example, the bank_method field is added, and you will need to register your fields.

Work with fields via meta, so as not to redefine all package interfaces.

https://github.com/bavix/laravel-wallet/blob/a9c30b7bac2d4ab354db74e0828de432203a177b/tests/Units/Domain/WalletExtensionTest.php#L31-L38

**Comment by hamedkhorasani** [comment]
**@rez1dent3** Thank you for your response.
Does adding a key in the meta field to establish a relationship in the database reduce performance?

**Comment by rez1dent3** [comment]
> Does adding a key in the meta field to establish a relationship in the database reduce performance?

The answer to the question depends heavily on the database.

Adding columns has an effect, but the meta field already exists and is filled in. It all depends on the volume and database.

**Comment by hamedkhorasani** [comment]
In the following code, I receive an error when assigning a value to the added field.

```
/** @var $firstWallet \Bavix\Wallet\Interfaces\Wallet */
$transfer = $firstWallet->transfer($secondWallet, 500, new Extra(
    deposit: ['message' => 'Hello, secondWallet!'],
    withdraw: new Option(
          meta: ['something' => 'anything'], 
          confirmed: false,
          added_field: "value"
    )
));
```

**Comment by rez1dent3** [comment]
Since there are no more questions, I will close the issue.
There will be additional questions - it is better to create a new issue.
